//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDocumentary.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentIndex()
        {
            this.DocumentIndex1 = new HashSet<DocumentIndex>();
        }
    
        public int index_id { get; set; }
        public string title { get; set; }
        public Nullable<int> document_id { get; set; }
        public Nullable<int> page_number { get; set; }
        public Nullable<int> parent_index_id { get; set; }
        public Nullable<int> author_id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentIndex> DocumentIndex1 { get; set; }
        public virtual DocumentIndex DocumentIndex2 { get; set; }
    }
}
