//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDocumentary.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentIndexes = new HashSet<DocumentIndex>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string file_path { get; set; }
        public Nullable<int> folder_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by_user_access_id { get; set; }
        public string link_to_image { get; set; }
        public string document_type { get; set; }
        public Nullable<int> document_status { get; set; }
        public Nullable<int> author_id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual UserAccess UserAccess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentIndex> DocumentIndexes { get; set; }
    }
}
