//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalDocumentary.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccess()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int id { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> read_limit { get; set; }
        public Nullable<int> read_full { get; set; }
        public Nullable<int> download { get; set; }
        public Nullable<int> page_read { get; set; }
        public Nullable<int> page_download { get; set; }
        public Nullable<int> user_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
